services:
  gitlab:
    image: gitlab/gitlab-ee:16.11.6-ee.0
    platform: linux/amd64
    container_name: ${INTERNAL_GITLAB_HOSTNAME}
    restart: always
    hostname: gitlab.bd
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${INTERNAL_GITLAB_HOSTNAME}/gitlab/'
    networks:
      - gitlab-network
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'
    shm_size: '256m'

  gitlab-runner:
    image: 'gitlab/gitlab-runner:v16.11.2'
    container_name: gitlab-runner
    restart: unless-stopped
    depends_on:
      - gitlab
    networks:
      - gitlab-network
    volumes:
      - './runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - "8093:8093"
    expose:
      - "80"
networks:
  gitlab-network:
    driver: bridge